version: '3'

services:
    webserver:
        build: .
        ports:
            - "5001:5000"
        depends_on:
            - db
        environment:
            MONGODB_HOSTNAME: db
            PORT: 5000
            SECRET_KEY: $SECRET_KEY
            DEBUG: "True"
            PYTHONHASHSEED: 0
    db:
        image: mongo:latest
        ports:
            - "5002:27017"